name = "vpn"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true

routes = [
  { pattern = "kingsvless.biz.id", custom_domain = true },
  { pattern = "ava.game.naver.com.kingsvless.biz.id", custom_domain = true },
  { pattern = "quiz.int.vidio.com.kingsvless.biz.id", custom_domain = true },
  { pattern = "graph.instagram.com.kingsvless.biz.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.kingsvless.biz.id", custom_domain = true },
  { pattern = "support.zoom.us.kingsvless.biz.id", custom_domain = true },  
  { pattern = "cache.netflix.com.kingsvless.biz.id", custom_domain = true },
]

[[kv_namespaces]]
binding = "SIREN"
id = "8cb7eada819e43ffad5d2f1420ed44e8"
[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "aaaaaaa1-bbbb-4ccc-addd-eeeeeeeeeee1"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/XLimite/vpn/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/XLimite/vpn/refs/heads/master/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/XLimite/vpn/refs/heads/master/web/web.html"
VMESS_PAGE_URL = "https://raw.githubusercontent.com/XLimite/vpn/refs/heads/master/web/vmess.html"
VLESS_PAGE_URL = "https://raw.githubusercontent.com/XLimite/vpn/refs/heads/master/web/vless.html"
CONVERTER_PAGE_URL = "https://raw.githubusercontent.com/XLimite/vpn/refs/heads/master/web/converter.html"
