name = "vpn"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true

routes = [
  { pattern = "free.kingsvless.biz.id", custom_domain = true },
  { pattern = "ava.game.naver.com.free.kingsvless.biz.id", custom_domain = true },
  { pattern = "quiz.int.vidio.com.free.kingsvless.biz.id", custom_domain = true },
  { pattern = "graph.instagram.com.free.kingsvless.biz.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.free.kingsvless.biz.id", custom_domain = true },
  { pattern = "support.zoom.us.free.kingsvless.biz.id", custom_domain = true },  
  { pattern = "cache.netflix.com.free.kingsvless.biz.id", custom_domain = true },
]

[[kv_namespaces]]
binding = "SIREN"
id = "8cb7eada819e43ffad5d2f1420ed44e8"
[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "20800721-d3fd-4c1f-81fc-a786f10b2f64"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/XLimite/vpn/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/XLimite/vpn/refs/heads/master/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/XLimite/vpn/refs/heads/master/web/link.html"
